index:
    path: /
    controller: App\Controller\UserController::index
    methods: GET

add_user:
    path: /add_user
    controller: App\Controller\UserController::login
    methods: GET

register_user:
    path: /register_user
    controller: App\Controller\UserController::registerUser
    
view_user:
    path: /view_user
    controller: App\Controller\UserController::viewUser
    methods: GET

view_users:
    path: /view_users
    controller: App\Controller\UserController::viewUsers
    methods: GET

update_user:
    path: /update_user
    controller: App\Controller\UserController::updateUser
    methods: POST|GET

delete_user:
    path: /delete_user
    controller: App\Controller\UserController::deleteUser
    methods: GET
