<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFgQ2dLT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFgQ2dLT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFgQ2dLT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFgQ2dLT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFgQ2dLT\App_KernelDevDebugContainer([
    'container.build_hash' => 'FgQ2dLT',
    'container.build_id' => 'a73bf979',
    'container.build_time' => 1716633931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFgQ2dLT');
